### PR TITLE
Update code for SI fast correctors analysis

### PR DESCRIPTION
**Pull request by xresende**

### CODE REVIEW

**Review by anacso17 — APPROVED** [review]

**Comment by anacso17** [comment]
@xresende could you please update version in this PR?

**Review by fernandohds564 — APPROVED** [review]

**Review by murilobalves — APPROVED** [review]

**Review by LuanaVilela — CHANGES_REQUESTED** [review]
The correctors that were already installed in the C2 sections are not listed here. Shouldn't they be included in the analysis?

**Comment by xresende** [comment]
> @xresende could you please update version in this PR?

done

**Comment by xresende** [comment]
> @xresende could you please update version in this PR?

yes, I missed going back and adding to the script! thanks, @LuanaVilela !
done. i also updated PR https://github.com/lnls-sirius/control-system-constants/pull/254 in csconsts

**Review by LuanaVilela — APPROVED** [review]

**Review by murilobalves — APPROVED** [review]

**Review by fernandohds564 — APPROVED** [review]

**Review by anacso17 — APPROVED** [review]

**Pull request merged**
